default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch('DATABASE_URL', 'abreu_poc_development') %>

test:
  <<: *default
  database: <%= ENV.fetch('DATABASE_URL', 'abreu_poc_test') %>

production:
  url: <%= ENV['DATABASE_CONNECTION_POOL_URL'] || ENV['DATABASE_URL'] %>
  prepared_statements: false
