name: CI

on:
  push:
    branches-ignore:
      - main

jobs:
  rspec:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: ci

    # services:
    #   postgres:
    #     env:
    #       POSTGRES_DB: postgres
    #       POSTGRES_PASSWORD: postgres
    #       POSTGRES_USER: postgres
    #     image: postgres:15.3
    #     ports:
    #       - 5432:5432
    #     options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    #   redis:
    #     image: redis:latest
    #     ports:
    #       - 6379:6379

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.5
          bundler-cache: true
          cache-version: 1

      - name: Install Dependencies
        run: |-
          sudo apt-get update
          sudo apt-get install -y libxml2-utils
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" | sudo tee  /etc/apt/sources.list.d/pgdg.list
          sudo apt-get update
          sudo apt-get install -y postgresql-client-15 psmisc

      # - name: Unit Test with RSpec
      #   # run: bundle exec parallel_test spec packs/**/spec -t rspec
      #   run: |-
      #     bundle exec rails db:create db:schema:load RAILS_ENV=ci
      #     bundle exec rspec

      # - name: Run Rubocop
      #   run: bundle exec rubocop
